---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt]
      - recipe[ngrok]
    attributes:
      ngrok:
        auth_token: Dmf3sPHijAG41E4wCGZh_5jVzT1LwzfHBKqnndoETH
        tunnels:
          kitchen-ci-test-vm:
            proto: http
            addr: 80
  - name: lwrp
    run_list:
      - recipe[apt]
      - recipe[fake]
    attributes:
      ngrok:
        auth_token: Dmf3sPHijAG41E4wCGZh_5jVzT1LwzfHBKqnndoETH